import os
import re
from datetime import datetime, timezone, timedelta

import psycopg
from psycopg.rows import dict_row
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
if not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL is missing. Add your Voroa PostgreSQL connection URL to .env."
    )


def now_utc():
    return datetime.now(timezone.utc)


def iso(dt):
    return dt.astimezone(timezone.utc).isoformat()


def parse_dt(value):
    if isinstance(value, datetime):
        if value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)
        return value
    return datetime.fromisoformat(value)


def connect():
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


def init_db():
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    user_id BIGINT PRIMARY KEY,
                    access_expires_at TEXT,
                    monitoring_enabled INTEGER NOT NULL DEFAULT 1,
                    paused_at TEXT
                )
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS keywords (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    keyword TEXT NOT NULL,
                    UNIQUE(user_id, keyword),
                    FOREIGN KEY(user_id) REFERENCES users(user_id)
                )
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS access_codes (
                    code TEXT PRIMARY KEY,
                    created_at TEXT NOT NULL,
                    duration_seconds BIGINT NOT NULL DEFAULT 86400,
                    activated_by BIGINT,
                    activated_at TEXT,
                    expires_at TEXT
                )
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS monitored_chats (
                    chat_id BIGINT PRIMARY KEY,
                    title TEXT NOT NULL,
                    username TEXT,
                    chat_type TEXT,
                    last_seen_at TEXT NOT NULL,
                    admin_monitored INTEGER NOT NULL DEFAULT 0
                )
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS user_monitored_chats (
                    user_id BIGINT NOT NULL,
                    chat_id BIGINT NOT NULL,
                    added_at TEXT NOT NULL,
                    PRIMARY KEY (user_id, chat_id),
                    FOREIGN KEY(user_id) REFERENCES users(user_id),
                    FOREIGN KEY(chat_id) REFERENCES monitored_chats(chat_id)
                )
            """)

            # Safe migrations for databases created by an earlier PostgreSQL version.
            for table, column, definition in [
                ("users", "monitoring_enabled", "INTEGER NOT NULL DEFAULT 1"),
                ("users", "paused_at", "TEXT"),
                ("monitored_chats", "admin_monitored", "INTEGER NOT NULL DEFAULT 0"),
                ("access_codes", "duration_seconds", "BIGINT NOT NULL DEFAULT 86400"),
                ("access_codes", "activated_by", "BIGINT"),
                ("access_codes", "activated_at", "TEXT"),
                ("access_codes", "expires_at", "TEXT"),
            ]:
                cur.execute("""
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = %s
                      AND column_name = %s
                """, (table, column))
                if cur.fetchone() is None:
                    cur.execute(
                        f'ALTER TABLE "{table}" ADD COLUMN "{column}" {definition}'
                    )

            cur.execute("UPDATE users SET monitoring_enabled=1 WHERE monitoring_enabled IS NULL")


def ensure_user(user_id):
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO users(user_id, monitoring_enabled)
                VALUES (%s, 1)
                ON CONFLICT(user_id) DO NOTHING
                """,
                (int(user_id),),
            )


def get_user_expiry(user_id):
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT access_expires_at FROM users WHERE user_id=%s",
                (int(user_id),),
            )
            row = cur.fetchone()
    if not row or not row["access_expires_at"]:
        return None
    return parse_dt(row["access_expires_at"])


def has_active_access(user_id):
    expiry = get_user_expiry(user_id)
    return expiry is not None and expiry > now_utc()


def set_user_access(user_id, expires_at):
    ensure_user(user_id)
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE users
                SET access_expires_at=%s, monitoring_enabled=1, paused_at=NULL
                WHERE user_id=%s
                """,
                (iso(expires_at), int(user_id)),
            )


def is_monitoring_enabled(user_id):
    ensure_user(user_id)
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT monitoring_enabled FROM users WHERE user_id=%s",
                (int(user_id),),
            )
            row = cur.fetchone()
    return bool(row and row["monitoring_enabled"])


def pause_monitoring(user_id):
    ensure_user(user_id)
    now = now_utc()
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT access_expires_at, monitoring_enabled, paused_at
                FROM users WHERE user_id=%s
                """,
                (int(user_id),),
            )
            row = cur.fetchone()
            if not row or not row["access_expires_at"]:
                return False, "no_access"
            expiry = parse_dt(row["access_expires_at"])
            if expiry <= now:
                return False, "expired"
            if not bool(row["monitoring_enabled"]):
                return False, "already_paused"
            cur.execute(
                """
                UPDATE users SET monitoring_enabled=0, paused_at=%s
                WHERE user_id=%s
                """,
                (iso(now), int(user_id)),
            )
    return True, "ok"


def resume_monitoring(user_id):
    ensure_user(user_id)
    now = now_utc()
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT access_expires_at, monitoring_enabled, paused_at
                FROM users WHERE user_id=%s
                """,
                (int(user_id),),
            )
            row = cur.fetchone()
            if not row or not row["access_expires_at"]:
                return False, "no_access", None
            expiry = parse_dt(row["access_expires_at"])
            if bool(row["monitoring_enabled"]):
                return False, "already_running", expiry
            paused_at = parse_dt(row["paused_at"]) if row["paused_at"] else None
            if not paused_at:
                return False, "not_paused", expiry
            new_expiry = expiry + (now - paused_at)
            cur.execute(
                """
                UPDATE users
                SET access_expires_at=%s, monitoring_enabled=1, paused_at=NULL
                WHERE user_id=%s
                """,
                (iso(new_expiry), int(user_id)),
            )
    return True, "ok", new_expiry


def add_keyword(user_id, keyword):
    ensure_user(user_id)
    keyword = keyword.strip()
    if not keyword:
        return False
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO keywords(user_id, keyword)
                VALUES (%s, %s)
                ON CONFLICT(user_id, keyword) DO NOTHING
                """,
                (int(user_id), keyword),
            )
            return cur.rowcount > 0


def remove_keyword(user_id, keyword):
    keyword = keyword.strip()
    if not keyword:
        return False
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                DELETE FROM keywords
                WHERE user_id=%s AND LOWER(keyword)=LOWER(%s)
                """,
                (int(user_id), keyword),
            )
            return cur.rowcount > 0


def get_keywords(user_id):
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT keyword FROM keywords WHERE user_id=%s ORDER BY id",
                (int(user_id),),
            )
            rows = cur.fetchall()
    return [row["keyword"] for row in rows]


def get_all_active_keyword_users():
    now = iso(now_utc())
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT u.user_id, k.keyword
                FROM users u
                JOIN keywords k ON k.user_id = u.user_id
                WHERE u.access_expires_at IS NOT NULL
                  AND u.access_expires_at > %s
                  AND u.monitoring_enabled = 1
                ORDER BY u.user_id, k.id
            """, (now,))
            rows = cur.fetchall()

    result = {}
    for row in rows:
        result.setdefault(int(row["user_id"]), []).append(row["keyword"])
    return result


def create_access_code(code, created_at, duration_seconds):
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO access_codes(code, created_at, duration_seconds)
                VALUES (%s, %s, %s)
                """,
                (code, iso(created_at), int(duration_seconds)),
            )


def activate_access_code(code, user_id, activated_at):
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT code, duration_seconds, activated_by, expires_at
                FROM access_codes WHERE code=%s
                """,
                (code,),
            )
            row = cur.fetchone()
            if not row:
                return False, "invalid", None
            if row["activated_by"] is not None:
                return False, "used", None

            expires_at = activated_at + timedelta(seconds=int(row["duration_seconds"]))
            cur.execute(
                """
                UPDATE access_codes
                SET activated_by=%s, activated_at=%s, expires_at=%s
                WHERE code=%s AND activated_by IS NULL
                """,
                (int(user_id), iso(activated_at), iso(expires_at), code),
            )
            if cur.rowcount != 1:
                conn.rollback()
                return False, "used", None

    set_user_access(user_id, expires_at)
    return True, "ok", expires_at


def get_access_codes():
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT code, created_at, duration_seconds, activated_by, activated_at, expires_at
                FROM access_codes
                ORDER BY created_at DESC
            """)
            rows = cur.fetchall()
    return [dict(row) for row in rows]


def get_customers():
    now = now_utc()
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT
                    u.user_id,
                    u.access_expires_at,
                    u.monitoring_enabled,
                    u.paused_at,
                    COUNT(k.id) AS keyword_count,
                    MAX(ac.activated_at) AS last_activated_at
                FROM users u
                LEFT JOIN keywords k ON k.user_id = u.user_id
                LEFT JOIN access_codes ac ON ac.activated_by = u.user_id
                GROUP BY u.user_id
                ORDER BY
                    CASE
                        WHEN u.access_expires_at IS NOT NULL
                         AND u.access_expires_at > %s
                        THEN 0 ELSE 1
                    END,
                    u.access_expires_at DESC,
                    u.user_id
            """, (iso(now),))
            rows = cur.fetchall()
    return [dict(row) for row in rows]


def upsert_monitored_chat(chat_id, title, username=None, chat_type=None):
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                INSERT INTO monitored_chats(
                    chat_id, title, username, chat_type, last_seen_at, admin_monitored
                )
                VALUES (%s, %s, %s, %s, %s, 0)
                ON CONFLICT(chat_id) DO UPDATE SET
                    title=EXCLUDED.title,
                    username=EXCLUDED.username,
                    chat_type=EXCLUDED.chat_type,
                    last_seen_at=EXCLUDED.last_seen_at
            """, (
                int(chat_id),
                title or "Unknown",
                username,
                chat_type,
                iso(now_utc()),
            ))


def get_monitored_chats():
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT chat_id, title, username, chat_type, last_seen_at, admin_monitored
                FROM monitored_chats
                ORDER BY chat_type, LOWER(title)
            """)
            rows = cur.fetchall()
    return [dict(row) for row in rows]


def find_monitored_chat(value):
    value = str(value).strip()
    if not value:
        return None

    with connect() as conn:
        with conn.cursor() as cur:
            row = None

            if re.fullmatch(r"-?\d+", value):
                cur.execute("""
                    SELECT chat_id, title, username, chat_type, last_seen_at, admin_monitored
                    FROM monitored_chats WHERE chat_id=%s
                """, (int(value),))
                row = cur.fetchone()

            if row is None:
                username = value.lstrip("@").lower()
                cur.execute("""
                    SELECT chat_id, title, username, chat_type, last_seen_at, admin_monitored
                    FROM monitored_chats
                    WHERE LOWER(COALESCE(username, ''))=%s
                """, (username,))
                row = cur.fetchone()

            if row is None:
                cur.execute("""
                    SELECT chat_id, title, username, chat_type, last_seen_at, admin_monitored
                    FROM monitored_chats
                    WHERE LOWER(title)=LOWER(%s)
                    ORDER BY last_seen_at DESC
                    LIMIT 1
                """, (value,))
                row = cur.fetchone()

    return dict(row) if row else None


def set_admin_monitored_chat(chat_id, enabled=True):
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "UPDATE monitored_chats SET admin_monitored=%s WHERE chat_id=%s",
                (1 if enabled else 0, int(chat_id)),
            )
            return cur.rowcount > 0


def get_admin_monitored_chats():
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT chat_id, title, username, chat_type, last_seen_at, admin_monitored
                FROM monitored_chats
                WHERE admin_monitored=1
                ORDER BY chat_type, LOWER(title)
            """)
            rows = cur.fetchall()
    return [dict(row) for row in rows]


def get_admin_monitored_chat_ids():
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT chat_id FROM monitored_chats WHERE admin_monitored=1"
            )
            rows = cur.fetchall()
    return {int(row["chat_id"]) for row in rows}


def add_user_monitored_chat(user_id, chat_id):
    ensure_user(user_id)
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT 1 FROM monitored_chats WHERE chat_id=%s",
                (int(chat_id),),
            )
            if not cur.fetchone():
                return False
            cur.execute(
                """
                INSERT INTO user_monitored_chats(user_id, chat_id, added_at)
                VALUES (%s, %s, %s)
                ON CONFLICT(user_id, chat_id) DO NOTHING
                """,
                (int(user_id), int(chat_id), iso(now_utc())),
            )
            return cur.rowcount > 0


def remove_user_monitored_chat(user_id, chat_id):
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "DELETE FROM user_monitored_chats WHERE user_id=%s AND chat_id=%s",
                (int(user_id), int(chat_id)),
            )
            return cur.rowcount > 0


def get_user_monitored_chats(user_id):
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT m.chat_id, m.title, m.username, m.chat_type, m.last_seen_at
                FROM user_monitored_chats um
                JOIN monitored_chats m ON m.chat_id = um.chat_id
                WHERE um.user_id=%s
                ORDER BY m.chat_type, LOWER(m.title)
            """, (int(user_id),))
            rows = cur.fetchall()
    return [dict(row) for row in rows]


def get_user_monitored_chat_ids(user_id):
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT chat_id FROM user_monitored_chats WHERE user_id=%s",
                (int(user_id),),
            )
            rows = cur.fetchall()
    return {int(row["chat_id"]) for row in rows}


def get_chat_monitored_users(chat_id):
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT user_id FROM user_monitored_chats WHERE chat_id=%s ORDER BY user_id",
                (int(chat_id),),
            )
            rows = cur.fetchall()
    return [int(row["user_id"]) for row in rows]


def add_monitor_for_user(user_id, chat_id):
    return add_user_monitored_chat(user_id, chat_id)


def remove_monitor_for_user(user_id, chat_id):
    return remove_user_monitored_chat(user_id, chat_id)


def revoke_user_access(user_id):
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE users
                SET access_expires_at=NULL, monitoring_enabled=0, paused_at=NULL
                WHERE user_id=%s
                """,
                (int(user_id),),
            )
            return cur.rowcount > 0
